name: mutable_copy_generator
description: Mutable copy generator simplify copy of immutable object. Unlike CopyWith allow to set null value
version: 0.2.6
repository: https://github.com/AlexVegner/mutable_copy_generator
issue_tracker: https://github.com/AlexVegner/mutable_copy_generator/issues
homepage: https://github.com/AlexVegner/mutable_copy_generator
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.2.1
  path: ^1.8.0
  source_gen: ^1.2.1

dev_dependencies:
  build_config: ^1.0.0
  build_runner: ^2.1.7
